name: ci-golang-workflow

on:
  pull_request:
    branches:
      - develop
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
    strategy:
      matrix:
        go: ['1.14','1.15']

      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Go environment
        uses: actions/setup-go@v2
        with:
          go-version: ${{matrix.go}}

      - name: Run tests
        run: go test
 
      - name: Run the application
        run: go run math.go
