name: ci-golang-workflow

on: [push]

jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Go environment
        uses: actions/setup-go@v2
        with:
          go-version: '1.15'

      - name: Run tests
        run: go test

      - name: Run the application
        run: go run math.go
